set_switchbot_curtain_position:
  name: Set SwitchBot Curtain Position
  description: Sets cover position with a specific speed profile.
  fields:
    entity_id:
      name: Entity
      description: The SwitchBot Curtain cover entity.
      required: true
      selector:
        entity:
          domain: cover
          multiple: true
    position:
      name: Position
      description: Target position (0% Closed - 100% Open).
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    speed:
      name: Speed Profile
      description: Select the movement speed.
      default: Normal
      selector:
        select:
          options:
            - QuietDrift
            - Silent
            - Normal
